#!/usr/bin/python3
# -*- coding: cp1252 -*-
import sys
def calcular_cost_pont(n, h, alpha, beta, xs, ys):

	  #cost1: acueducto (iterativo)
    #calcular el sumatorio de hi y di y calcular coste
    sumh = 0
    sumd = 0
    for i in range(n):
        sumh += h - ys[i]
        if (i != 0):
            sumd += (xs[i] - xs[i-1])**2
    cost1 = alpha*sumh + beta*sumd

	  #cost2: puente
    sumh = (h - ys[0]) + (h - ys[n-1])
    sumd = (xs[n-1] - xs[0])**2
    cost2 = alpha*sumh + beta*sumd
	
    #buscar el mejor coste
    if cost1 <= cost2:
        print(cost1)
    else:
        print(cost2)

if len(sys.argv) == 2:
    #abrir el fichero y leer la primera linea (split para separar los datos)
    f = open(sys.argv[1])
    datos = f.readline()
    datos2 = datos.split()
    
	#guardar datos de la primera linea
    n = int(datos2[0])
    h = int(datos2[1])
    alpha = int(datos2[2])
    beta = int(datos2[3])

	#guardar coordenadas de los puntos
    xs = [0 for _ in range(n)]
    ys = [0 for _ in range(n)]
    for i in range(n):
        datos = f.readline()
        datos2 = datos.split()
        xs[i] = int(datos2[0])
        ys[i] = int(datos2[1])
    
    f.close()
    calcular_cost_pont(n, h, alpha, beta, xs, ys)
